#!/bin/sh

set -e

URL='https://www.evangelikus.hu/hitunk/lelki-taplalek?napiigenap='

start_date="$1"
number_of_days="$2"

for i in `seq 0 $number_of_days`
do
    tmp_file=$(mktemp)

    datum=$(date -d "$start_date $i days" +%Y-%m-%d)
    echo "$datum:"
    curl -s "$URL$datum" > "$tmp_file"
    cat "$tmp_file" \
        | pup 'h5:contains("Napi igék") + div div:first-child text{}' \
        | head -n 1 \
        | sed 's/ *( *$//'
    cat "$tmp_file" \
        | pup 'h5:contains("Napi igék") + div div:first-child div.uk-inline:first-child a:contains("Szentírás.hu")' \
        | tr '\n' ' ' \
        | sed 's:<a *href="\(.*\)/\([^"]*\)".*:<a href="\1/\2" target="_blank">\2</a>:'

    printf "\n\n\n"

    rm "$tmp_file"
done
